name: ğŸ’¥ Terraform Destroy (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to destroy?"
        type: choice
        required: true
        options:
          - dev
          - preprod
          - prod

env:
  TF_IN_AUTOMATION: "true"

jobs:
  destroy:
    name: "Destroy - ${{ inputs.environment }}"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: envs/${{ inputs.environment }}

    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v4

      - name: ğŸ§° Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: ğŸ” Azure Login (dev)
        if: inputs.environment == 'dev'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: ğŸ” Azure Login (preprod)
        if: inputs.environment == 'preprod'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PREPROD }}

      - name: ğŸ” Azure Login (prod)
        if: inputs.environment == 'prod'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: ğŸŒ Terraform Init
        run: terraform init -reconfigure

      - name: ğŸ’¥ Terraform Destroy
        run: terraform destroy -auto-approve -var-file="${{ inputs.environment }}.tfvars"
